# apps/authentication/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
import uuid
from datetime import timedelta
import pyotp
from django.core.validators import MinLengthValidator

class EmailVerificationToken(models.Model):
    """Stores tokens for verifying user email addresses."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Verification token for {self.user.email}"

    @property
    def is_expired(self):
        """Check if the token is older than the expiry duration (e.g., 1 hour)."""
        expiry_duration = timedelta(hours=1) # Make this configurable in settings if needed
        return timezone.now() > self.created_at + expiry_duration
    
class PasswordResetToken(models.Model):
    """Stores tokens for resetting user passwords."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Password reset token for {self.user.email}"

    @property
    def is_expired(self):
        """Check if the token is older than the expiry duration (e.g., 1 hour)."""
        expiry_duration = timedelta(hours=1) # Make configurable
        return timezone.now() > self.created_at + expiry_duration
    
class TwoFactorSecret(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='otp_secret')
    # Store the base32 encoded secret key generated by pyotp
    secret_key = models.CharField(max_length=100) # Adjust length as needed
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"2FA Secret for {self.user.username}"

    def get_provisioning_uri(self, issuer_name=None):
        """Generates the provisioning URI for QR code."""
        issuer = issuer_name or getattr(settings, 'OTP_TOTP_ISSUER', 'NetPlay')
        return pyotp.totp.TOTP(self.secret_key).provisioning_uri(
            name=self.user.email, # Use email or username in authenticator app
            issuer_name=issuer
        )

    def verify_code(self, code):
        """Verifies a TOTP code."""
        totp = pyotp.totp.TOTP(self.secret_key)
        return totp.verify(code, valid_window=1) # Allow for slight time drift (1 window = 30s)


# Store backup codes (hashed)
class BackupCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='backup_codes')
    code_hash = models.CharField(max_length=128, default='') # Store hash of the code
    is_used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Backup code for {self.user.username} (Used: {self.is_used})"

    def verify_code(self, plain_code):
        """Verifies a plain backup code against the stored hash."""
        from django.contrib.auth.hashers import check_password
        # Use a suitable hashing algorithm, Argon2 is good, but check_password handles it
        return check_password(plain_code, self.code_hash)
    
class AccountUnlockToken(models.Model):
    """Stores tokens for unlocking user accounts."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='unlock_tokens')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Unlock token for {self.user.username}"

    @property
    def is_expired(self):
        """Check if the token is older than the expiry duration (e.g., 15 minutes)."""
        expiry_duration = timedelta(minutes=15) # Shorter expiry for unlock
        return timezone.now() > self.created_at + expiry_duration

# Add other auth-related models here later (PasswordResetToken, TwoFactorSecret, BackupCode etc.)